### ISSUE TITLE
App does not load, empty page

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/LAI-Echo-App#103]
![image](https://user-images.githubusercontent.com/6035284/198310407-25b21c10-87fb-4703-9b1e-507417fe9543.png)

**Comment by alecmerdler** [comment]
@Borda Was this in an Incognito Window in Chrome? Your issue seems similar to [this StackOverflow question](https://stackoverflow.com/questions/24456891/iframe-in-chrome-error-uncaught-securityerror-failed-to-read-the-sessionstora), which indicates that you need to change your privacy settings to allow `localStorage` to be used by websites.

**Comment by Borda** [comment]
> @Borda Was this in an Incognito Window in Chrome? Your issue seems similar to [this StackOverflow question](https://stackoverflow.com/questions/24456891/iframe-in-chrome-error-uncaught-securityerror-failed-to-read-the-sessionstora), which indicates that you need to change your privacy settings to allow `localStorage` to be used by websites.

nop, it was a normal window, but anyway, how any user would know what to do if nothing shows? :)
